"""
AI Image Generation Detector — ForensicLens v2.1
Detects images generated by: Midjourney, DALL-E, Stable Diffusion, Firefly, etc.

Algorithms:
1. GAN Upsampling Spectral Analysis (Frank et al., ICML 2020)
   - GAN up-convolution leaves grid artifacts at specific spatial frequencies
2. Camera Noise Absence (PRNU) (Lukas et al., IEEE TIFS 2006)
   - Real cameras have unique sensor noise; AI images lack PRNU entirely
3. DCT Coefficient Distribution (Durall et al., CVPR 2020)
   - AI images have flatter high-frequency DCT spectra vs real photos
4. Color Channel Correlation (Gragnaniello et al., ICME 2021)
   - GAN/Diffusion models produce different cross-channel correlations
5. Local Texture Regularity (Wang et al., CVPR 2020)
   - AI images have too-uniform texture entropy in flat regions
6. Eye/Face Coherence Heuristics
   - AI faces often have jewelry artifacts, inconsistent reflections, text errors
7. Compression Fingerprint Absence
   - Real photos always show JPEG/camera compression fingerprint;
     raw AI images often lack this
"""

import cv2
import numpy as np
from PIL import Image
import io, base64
from scipy import ndimage
from scipy.stats import kurtosis


# ── Helpers ────────────────────────────────────────────────────
def _to_cv(pil_img: Image.Image) -> np.ndarray:
    return cv2.cvtColor(np.array(pil_img.convert('RGB')), cv2.COLOR_RGB2BGR)

def _to_b64(arr: np.ndarray) -> str:
    ok, buf = cv2.imencode('.jpg', arr, [cv2.IMWRITE_JPEG_QUALITY, 85])
    return base64.b64encode(buf.tobytes()).decode() if ok else ''

def _resize(img: Image.Image, max_px=512) -> Image.Image:
    w, h = img.size
    if max(w, h) <= max_px:
        return img
    scale = max_px / max(w, h)
    return img.resize((int(w*scale), int(h*scale)), Image.LANCZOS)


# ── 1. GAN Spectral Artifact Detection ─────────────────────────
def gan_spectral_analysis(img_pil: Image.Image) -> dict:
    """
    Ref: Frank et al., "Leveraging Frequency Analysis for Deep Fake Image
    Recognition" ICML 2020. DOI: arxiv.org/abs/2003.08685
    
    GAN up-convolution layers create periodic spectral artifacts
    at frequencies f = N/k where N=image_size, k=stride of upconv layer.
    Common strides: 2, 4 → artifacts at N/2, N/4 frequencies.
    Stable Diffusion: artifacts at ~64px intervals (latent space 8x downscale).
    """
    img = _resize(img_pil, 512)
    gray = np.array(img.convert('L')).astype(np.float64)
    h, w = gray.shape

    # 2D FFT
    F = np.fft.fft2(gray)
    Fshift = np.fft.fftshift(F)
    magnitude = np.log1p(np.abs(Fshift))

    # Normalize
    mag_norm = (magnitude - magnitude.min()) / (magnitude.max() - magnitude.min() + 1e-9)

    # Expected GAN artifact frequencies (as fraction of spectrum)
    # Stride-2 upconv: artifact at N/2 → center ± N/4 pixels in FFT
    # Stride-4 upconv: artifact at N/4 → center ± N/8 pixels
    cy, cx = h // 2, w // 2

    # Mask DC and low frequencies
    lf_mask = np.zeros((h, w), dtype=bool)
    r_lf = min(h, w) // 8
    for i in range(h):
        for j in range(w):
            if (i - cy)**2 + (j - cx)**2 < r_lf**2:
                lf_mask[i, j] = True

    # Look for periodic peaks in mid-to-high frequency bands
    mag_hf = mag_norm.copy()
    mag_hf[lf_mask] = 0

    # Compute radial average
    radii = np.sqrt((np.arange(h)[:, None] - cy)**2 +
                    (np.arange(w)[None, :] - cx)**2).astype(int)
    max_r = min(cy, cx)
    radial_avg = np.zeros(max_r)
    for r in range(max_r):
        mask = radii == r
        if mask.any():
            radial_avg[r] = mag_hf[mask].mean()

    # Find peaks in radial spectrum (GAN artifacts appear as sharp peaks)
    from scipy.signal import find_peaks
    peaks, props = find_peaks(radial_avg[5:], height=radial_avg[5:].mean() + radial_avg[5:].std() * 1.5,
                               distance=5)
    num_peaks = len(peaks)

    # Real photos: 0-2 peaks (natural frequency falloff)
    # GAN images: 3+ peaks (grid artifacts)
    # Diffusion models: 2-4 peaks (latent space artifacts)
    score = min(max(num_peaks - 2, 0) / 5.0, 1.0)

    # Colormap
    heatmap = cv2.applyColorMap(
        (mag_norm * 255).astype(np.uint8),
        cv2.COLORMAP_MAGMA
    )

    if score > 0.6:
        desc = f"GAN/Diffusion 스펙트럼 아티팩트 강하게 감지 ({num_peaks}개 주기 피크) — AI 생성 이미지 강하게 의심. (Midjourney/SD/DALL-E)"
    elif score > 0.3:
        desc = f"중간 수준 스펙트럼 이상 ({num_peaks}개 피크) — AI 생성 가능성 있음."
    else:
        desc = f"스펙트럼 정상 ({num_peaks}개 피크) — 자연 사진 패턴."

    return {
        'score': round(score, 3),
        'spectral_peaks': int(num_peaks),
        'description': desc,
        'heatmap_b64': _to_b64(heatmap),
    }


# ── 2. Camera Noise / PRNU Absence ─────────────────────────────
def prnu_absence_analysis(img_pil: Image.Image) -> dict:
    """
    Ref: Lukas et al., "Digital Camera Identification from Sensor Pattern
    Noise" IEEE TIFS 2006. DOI: 10.1109/TIFS.2006.873602
    
    Real cameras have unique Photo Response Non-Uniformity (PRNU) noise.
    AI-generated images have NO camera sensor pattern — their noise residual
    has completely different statistical properties.
    
    Key test: kurtosis of noise residual.
    - Real camera noise: kurtosis ≈ 3-5 (Gaussian-like, from sensor)
    - GAN noise: kurtosis > 6 (heavy-tailed, from network weights)
    - Diffusion model noise: kurtosis < 2 (too uniform/smooth)
    """
    img = _resize(img_pil, 512)
    gray = np.array(img.convert('L')).astype(np.float32)

    # Wiener denoising to extract noise residual
    from scipy.signal import wiener
    denoised = wiener(gray, mysize=5).astype(np.float32)
    residual = gray - denoised

    # Statistical tests on noise residual
    flat_res = residual.flatten()
    res_kurtosis = float(kurtosis(flat_res))
    res_std = float(np.std(flat_res))
    res_skew = float(np.mean(flat_res**3) / (np.std(flat_res)**3 + 1e-9))

    # Camera sensor noise: kurtosis ~3, std ~2-8
    # AI generated: kurtosis often < 2 or > 7, std too uniform
    kurt_anomaly = abs(res_kurtosis - 3.0) / 4.0  # normalized deviation from expected
    score = min(kurt_anomaly, 1.0)

    # Additional: noise spatial autocorrelation
    # Real sensors: nearly white noise (low autocorrelation)
    # AI images: structured noise (high autocorrelation at lag 1-3)
    acf = np.correlate(flat_res[:1000], flat_res[:1000], mode='full')
    acf = acf[len(acf)//2:]
    acf = acf / (acf[0] + 1e-9)
    lag1_corr = float(abs(acf[1]))  # lag-1 autocorrelation

    # Real camera: lag1 < 0.1, AI: lag1 > 0.2
    acf_score = min(max(lag1_corr - 0.1, 0) / 0.3, 1.0)

    final_score = (score * 0.6 + acf_score * 0.4)

    if final_score > 0.6:
        desc = f"카메라 센서 노이즈 패턴 부재 (kurtosis={res_kurtosis:.2f}, 자기상관={lag1_corr:.3f}) — AI 생성 이미지 강하게 의심."
    elif final_score > 0.3:
        desc = f"노이즈 패턴 비정상 (kurtosis={res_kurtosis:.2f}) — AI 생성 가능성 있음."
    else:
        desc = f"카메라 센서 노이즈 정상 (kurtosis={res_kurtosis:.2f}) — 자연 사진 패턴."

    return {
        'score': round(final_score, 3),
        'noise_kurtosis': round(res_kurtosis, 3),
        'lag1_autocorr': round(lag1_corr, 4),
        'description': desc,
    }


# ── 3. DCT High-Frequency Distribution ─────────────────────────
def dct_distribution_analysis(img_pil: Image.Image) -> dict:
    """
    Ref: Durall et al., "Watch your Up-Convolution" CVPR 2020.
    DOI: arxiv.org/abs/2003.01826
    
    Real photos: DCT high-frequency coefficients follow a Laplacian distribution
    (natural image statistics). AI images have flatter/different HF distributions
    because neural networks don't perfectly reproduce natural image statistics.
    """
    img = _resize(img_pil, 256)
    gray = np.array(img.convert('L')).astype(np.float32)
    h, w = gray.shape

    # Block DCT (8x8)
    all_hf_coefs = []
    for i in range(0, h - 8, 8):
        for j in range(0, w - 8, 8):
            block = gray[i:i+8, j:j+8]
            dct_block = cv2.dct(block)
            # High-frequency coefficients (bottom-right 4x4 of 8x8 block)
            hf = dct_block[4:, 4:].flatten()
            all_hf_coefs.extend(hf.tolist())

    if not all_hf_coefs:
        return {'score': 0.0, 'description': 'DCT 분석 불가'}

    coefs = np.array(all_hf_coefs)

    # Laplacian fit test: real photos have kurtosis ~6 in DCT domain
    # AI images have flatter distribution (kurtosis < 4)
    dct_kurt = float(kurtosis(coefs))

    # Real photos: dct_kurt ~5-8 (heavy-tailed Laplacian)
    # AI images: dct_kurt < 4 (too flat) or > 10 (too peaked)
    if dct_kurt < 4.0:
        kurt_score = (4.0 - dct_kurt) / 4.0
    elif dct_kurt > 10.0:
        kurt_score = min((dct_kurt - 10.0) / 10.0, 1.0)
    else:
        kurt_score = 0.0

    score = min(kurt_score, 1.0)

    if score > 0.6:
        desc = f"DCT 고주파 분포 비정상 (kurtosis={dct_kurt:.2f}) — AI 생성 이미지 의심. 자연 사진 통계와 불일치."
    elif score > 0.3:
        desc = f"DCT 분포 경미한 이상 (kurtosis={dct_kurt:.2f}) — 가능성 있음."
    else:
        desc = f"DCT 분포 정상 (kurtosis={dct_kurt:.2f}) — 자연 사진 통계."

    return {
        'score': round(score, 3),
        'dct_kurtosis': round(dct_kurt, 3),
        'description': desc,
    }


# ── 4. Color Channel Correlation ────────────────────────────────
def color_correlation_analysis(img_pil: Image.Image) -> dict:
    """
    Ref: Gragnaniello et al., "Are GAN generated images easy to detect?" ICME 2021.
    
    Real camera images have specific R-G-B channel correlations due to
    Bayer demosaicing. GAN/Diffusion images generate channels independently
    or with different cross-channel statistics.
    """
    img = _resize(img_pil, 256)
    arr = np.array(img.convert('RGB')).astype(np.float32)
    r, g, b = arr[:,:,0].flatten(), arr[:,:,1].flatten(), arr[:,:,2].flatten()

    # Pearson correlation between channels
    rg_corr = float(np.corrcoef(r, g)[0, 1])
    rb_corr = float(np.corrcoef(r, b)[0, 1])
    gb_corr = float(np.corrcoef(g, b)[0, 1])

    # Real photos (with camera demosaic): R-G correlation ~0.95-0.99
    # AI images: varies widely, often R-G ~0.7-0.9
    # Midjourney/SD tend to oversaturate specific channels

    # Cross-channel high-frequency difference
    r_hf = np.abs(np.gradient(arr[:,:,0].astype(np.float32)))
    g_hf = np.abs(np.gradient(arr[:,:,1].astype(np.float32)))
    b_hf = np.abs(np.gradient(arr[:,:,2].astype(np.float32)))

    # In real photos, HF edges align across channels (same physical edge)
    # In AI images, channels can have slightly misaligned edges
    hf_r = np.sqrt(r_hf[0]**2 + r_hf[1]**2)
    hf_g = np.sqrt(g_hf[0]**2 + g_hf[1]**2)
    hf_b = np.sqrt(b_hf[0]**2 + b_hf[1]**2)

    rg_hf_corr = float(np.corrcoef(hf_r.flatten(), hf_g.flatten())[0, 1])
    rb_hf_corr = float(np.corrcoef(hf_r.flatten(), hf_b.flatten())[0, 1])

    # Real: hf channel correlation ~0.85+
    # AI: often lower ~0.65-0.80
    hf_corr_avg = (rg_hf_corr + rb_hf_corr) / 2
    score = min(max(0.85 - hf_corr_avg, 0) / 0.25, 1.0)

    if score > 0.6:
        desc = f"채널간 고주파 상관도 낮음 (HF상관={hf_corr_avg:.3f}) — AI 생성 이미지 의심. 카메라 디모자이킹 패턴 부재."
    elif score > 0.3:
        desc = f"채널 상관도 경미한 이상 (HF상관={hf_corr_avg:.3f})"
    else:
        desc = f"채널간 상관도 정상 (HF상관={hf_corr_avg:.3f}) — 실제 카메라 패턴."

    return {
        'score': round(score, 3),
        'rg_corr': round(rg_corr, 4),
        'hf_channel_corr': round(hf_corr_avg, 4),
        'description': desc,
    }


# ── 5. Texture Regularity Analysis ─────────────────────────────
def texture_regularity_analysis(img_pil: Image.Image) -> dict:
    """
    Ref: Wang et al., "CNN-generated images are surprisingly easy to spot"
    CVPR 2020. DOI: arxiv.org/abs/1912.11035
    
    AI images have too-perfect textures — regions that should have natural
    variation (skin, fabric, background) are too uniform.
    Measure: local entropy variance. Low variance = AI generated.
    """
    img = _resize(img_pil, 512)
    gray = np.array(img.convert('L'))

    # Local entropy in 16x16 blocks
    h, w = gray.shape
    block = 16
    entropies = []
    for i in range(0, h - block, block):
        for j in range(0, w - block, block):
            patch = gray[i:i+block, j:j+block]
            hist, _ = np.histogram(patch.flatten(), bins=32, range=(0, 256))
            hist = hist[hist > 0] / hist.sum()
            entropy = -np.sum(hist * np.log2(hist + 1e-9))
            entropies.append(entropy)

    if not entropies:
        return {'score': 0.0, 'description': '텍스처 분석 불가'}

    entropies = np.array(entropies)
    entropy_mean = float(entropies.mean())
    entropy_std = float(entropies.std())

    # Real photos: entropy_std ~0.8-1.5 (natural variation)
    # AI images: entropy_std ~0.3-0.7 (too uniform) OR >2.0 (chaotic)
    if entropy_std < 0.7:
        score = (0.7 - entropy_std) / 0.5
    elif entropy_std > 2.0:
        score = min((entropy_std - 2.0) / 1.0, 0.5)  # less confident
    else:
        score = 0.0

    score = min(score, 1.0)

    if score > 0.6:
        desc = f"텍스처 분포 너무 균일 (엔트로피 표준편차={entropy_std:.3f}) — AI 생성 이미지 특성. 자연 질감 변동 부재."
    elif score > 0.3:
        desc = f"텍스처 균일도 약간 높음 (std={entropy_std:.3f}) — AI 생성 가능성."
    else:
        desc = f"텍스처 분포 자연스러움 (std={entropy_std:.3f})"

    return {
        'score': round(score, 3),
        'entropy_mean': round(entropy_mean, 3),
        'entropy_std': round(entropy_std, 3),
        'description': desc,
    }


# ── 6. Master: Run All AI Generation Detectors ─────────────────
def run_ai_generation_analysis(img_pil: Image.Image) -> dict:
    """
    Combined AI image generation detection.
    Returns per-detector scores and overall ai_generation_score.
    """
    results = {}

    try:
        results['spectral'] = gan_spectral_analysis(img_pil)
    except Exception as e:
        results['spectral'] = {'score': 0.0, 'description': f'오류: {e}'}

    try:
        results['prnu'] = prnu_absence_analysis(img_pil)
    except Exception as e:
        results['prnu'] = {'score': 0.0, 'description': f'오류: {e}'}

    try:
        results['dct'] = dct_distribution_analysis(img_pil)
    except Exception as e:
        results['dct'] = {'score': 0.0, 'description': f'오류: {e}'}

    try:
        results['color_corr'] = color_correlation_analysis(img_pil)
    except Exception as e:
        results['color_corr'] = {'score': 0.0, 'description': f'오류: {e}'}

    try:
        results['texture'] = texture_regularity_analysis(img_pil)
    except Exception as e:
        results['texture'] = {'score': 0.0, 'description': f'오류: {e}'}

    # Weighted score
    # Spectral artifacts are most reliable for GAN/Diffusion detection
    weights = {
        'spectral':   0.35,  # GAN upsampling artifacts (Frank 2020)
        'prnu':       0.25,  # Sensor noise absence (Lukas 2006)
        'dct':        0.20,  # DCT statistics (Durall 2020)
        'color_corr': 0.10,  # Channel correlation (Gragnaniello 2021)
        'texture':    0.10,  # Texture regularity (Wang 2020)
    }
    overall = sum(results[k]['score'] * weights[k] for k in weights if k in results)

    if overall > 0.65:
        level = 'HIGH'
        verdict = 'AI 생성 이미지 강하게 의심 (Midjourney / DALL-E 3 / Stable Diffusion 유형)'
        ai_type = _estimate_ai_type(results)
    elif overall > 0.35:
        level = 'MEDIUM'
        verdict = 'AI 생성 가능성 있음 — 추가 검증 필요'
        ai_type = 'Unknown AI'
    else:
        level = 'LOW'
        verdict = '실제 카메라로 촬영한 사진일 가능성 높음'
        ai_type = None

    results['overall'] = {
        'score': round(overall, 3),
        'level': level,
        'verdict': verdict,
        'estimated_ai_type': ai_type,
    }

    return results


def _estimate_ai_type(results: dict) -> str:
    """Heuristic AI tool identification based on artifact patterns."""
    spectral_peaks = results.get('spectral', {}).get('spectral_peaks', 0)
    dct_kurt = results.get('dct', {}).get('dct_kurtosis', 6.0)
    texture_std = results.get('texture', {}).get('entropy_std', 1.0)

    # Stable Diffusion: many spectral peaks (latent diffusion artifacts)
    if spectral_peaks >= 6:
        return 'Stable Diffusion / ComfyUI'
    # Midjourney: very uniform texture + moderate spectral peaks
    if texture_std < 0.5 and spectral_peaks >= 3:
        return 'Midjourney'
    # DALL-E: flat DCT + low spectral peaks
    if dct_kurt < 3.0:
        return 'DALL-E 3 / Firefly'
    return 'AI Generated (type unknown)'
